### ISSUE TITLE
Once the solver does a match - the resource offer is wiped

### ISSUE THREAD

**Issue by binocarlos** [bacalhau-project/lilypad#13] opened 2023-07-07 17:41 UTC
Once the solver matches a job to a resource provider - it wipes the resource offer from the in memory state of the solver...

This means the resource provider will only do one job until we either:

 * change this behaviour (e.g. keep hold of the resource offer but then how do we rate limit)
 * re-register the resource offer once a job has completed

**Comment by lukemarsden** [comment] 2023-07-07 18:34
Dupe of #3

**Closed** 2023-07-10 12:38 UTC
